version: '3'

networks:
  backend:
    driver: bridge

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local

services:
  postgres:
    image: postgres:16-alpine
    container_name: teslo-shop-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: teslo-shop-pgadmin
    restart: always
    ports:
      - 8890:80
    environment:
      PGADMIN_DEFAULT_EMAIL: teslo-shop@example.com
      PGADMIN_DEFAULT_PASSWORD: 123456b
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - backend
